name: cli_buddy
description: CLI to call any AI to ask, auto-complete, and generate code directly from any command line tool.
version: 0.0.1-dev.1
homepage: https://rfway.org
repository: https://github.com/rezmeplxrf/cli_buddy
topics:
  - cli
  - http

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.1
  dio: ^5.6.0
  dotenv: ^4.2.0
  flat_buffers: ^23.5.26
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mason_logger: ^0.3.0
  objectbox: ^4.0.2
  pub_updater: ^0.5.0
  result_dart: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  objectbox_generator: any
  test: ^1.25.8
  very_good_analysis: ^6.0.0

executables:
  buddy:
