name: cli_buddy
description: A CLI tool to call any AI to ask, auto-complete, and generate code directly from any command line tool.
version: 0.2.0
homepage: https://github.com/rezmeplxrf/cli_buddy
repository: https://github.com/rezmeplxrf/cli_buddy
topics:
  - cli
  - ai
  - llm
  - tool

environment:
  sdk: ^3.5.0

platforms:
  linux:
  macos:
  windows:

dependencies:
  archive: ^3.6.1
  args: ^2.5.0
  barbecue: ^0.5.0
  cli_completion: ^0.5.1
  collection: ^1.18.0
  dio: ^5.6.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mason_logger: ^0.3.0
  path: ^1.9.0
  process_run: ^1.2.0
  pub_updater: ^0.5.0
  result_dart: ^1.1.1
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

executables:
  buddy:
