analyzer:
  errors:
    always_use_package_imports: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_print: ignore
    eol_at_end_of_file: ignore
    flutter_style_todos: ignore
    invalid_annotation_target: ignore
    library_private_types_in_public_api: ignore
    lines_longer_than_80_chars: ignore
    no_default_cases: ignore
    require_trailing_commas: ignore
    use_setters_to_change_properties: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.js"
    - "**/*.wasm"
    - "**/*.html"
    - "pubspec.yaml"
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
