name: buddy_chat
description: "Interface for cli_buddy"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.6.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  markdown_widget: ^2.3.2+6
  url_launcher: ^6.3.0
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  talker: ^4.4.1
  talker_dio_logger: ^4.4.1
  hooks_riverpod: ^2.5.2
  flex_color_scheme: ^7.3.1
  loading_animation_widget: ^1.2.1
  intl: ^0.19.0
  collection: ^1.18.0
  shared_preferences: ^2.3.2
  go_router: ^14.2.7
  flutter_easyloading:
    git:
      url: https://github.com/rezmeplxrf/flutter_easyloading.git
  web_socket_channel: ^3.0.1
  cli_buddy: any

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
